set -g base-index 1                         # Start window numbering at 1
set -g renumber-windows on                  # Renumber windows when one is closed
set -g mouse on                             # Enable mouse support
set -g default-terminal "tmux-256color"     # Enable true colour support (optional)
# set -ga terminal-overrides ",*256col*:Tc"
set -as terminal-features ",*:RGB"

# Change prefix from Ctrl-b → Alt-z
unbind C-b
set-option -g prefix M-z
bind-key M-z send-prefix
bind l send-keys C-l                        # use leader + l to clear terminal (ctrl+l used by vim-tmux-nav)

# bind h select-pane -L
# bind j select-pane -D
# bind k select-pane -U
# bind l select-pane -R
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# New pane inherits current pane's path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# copy keys
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# System clipboard integration (optional)
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"


### Plugins

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-net-speed'

### Theme (Catppuccin)

# set -g @catppuccin_status_background none
set -g @_ctp_status_bg "#{@thm_surface_0}"
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator ""
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_flags_icon_zoom " 󰁌"

set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_application_icon " "


%hidden MODULE_NAME="custom_ram"
set -g "@catppuccin_${MODULE_NAME}_icon" " "
set -g "@catppuccin_${MODULE_NAME}_color" "#{@thm_yellow}"
set -g "@catppuccin_${MODULE_NAME}_text" "#[fg=#{?ram_fg_color,#{ram_fg_color},#{@thm_crust}},bg=#{?ram_bg_color,#{ram_bg_color},#{@thm_yellow}}] ##{ram_percentage}"

set -gF @catppuccin_status_custom_ram_icon_bg "#{E:@thm_yellow}"
set -g @catppuccin_status_custom_ram_icon_fg "#11111b"

source "~/.config/tmux/plugins/catppuccin/tmux/utils/status_module.conf"

%hidden MODULE_NET="custom_net_speed"
set -g "@catppuccin_${MODULE_NET}_icon" "󰓅 "
set -g "@catppuccin_${MODULE_NET}_color" "#{@thm_yellow}"
set -g "@catppuccin_${MODULE_NET}_text" "##{net_speed}"

set -g @net_speed_interfaces "eth0 eth1 wlo1"
source "~/.config/tmux/plugins/catppuccin/tmux/utils/status_module.conf"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
set -g status-position top
set -g status-left ""
set -g status-left-length 100
set -g status-right-length 100
set -g status-right ""

set -g @catppuccin_status_background default
set -g @catppuccin_use_icons "yes"
set -g @catppuccin_window_icon_enable "yes"
set -g @catppuccin_date_time_text " %a %d-%b %H:%M"
set -ag status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"

set -agF status-right "#{E:@catppuccin_status_custom_net_speed}"
set -agF status-right "#{E:@catppuccin_status_date_time}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -ag status-left "#{E:@catppuccin_status_session}"

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

run '~/.tmux/plugins/tpm/tpm'

